<?php
/**
 * Identifier and timestamp helpers.
 *
 * @package GridRankers_Portal
 */

defined( 'ABSPATH' ) || exit;

/**
 * ULID ids (SPEC.md section 5) and UTC DATETIME strings.
 */
class GRP_Ids {

	/**
	 * Crockford base32 alphabet used by ULIDs.
	 */
	const ULID_ALPHABET = '0123456789ABCDEFGHJKMNPQRSTVWXYZ';

	/**
	 * Millisecond time of the last ULID generated by this process.
	 *
	 * @var int
	 */
	private static $last_time = -1;

	/**
	 * Random part (16 base32 digits) of the last ULID.
	 *
	 * @var int[]
	 */
	private static $last_random = array();

	/**
	 * A new 26-character ULID: 48-bit millisecond timestamp + 80 random bits.
	 *
	 * Monotonic within a process: ids made in the same millisecond increment the
	 * random part, so ordering by id matches creation order.
	 *
	 * @return string
	 */
	public static function ulid() {
		$time = (int) floor( microtime( true ) * 1000 );

		if ( $time <= self::$last_time ) {
			$time = self::$last_time;
			for ( $i = 15; $i >= 0; $i-- ) {
				if ( self::$last_random[ $i ] < 31 ) {
					++self::$last_random[ $i ];
					break;
				}
				self::$last_random[ $i ] = 0;
			}
		} else {
			$bytes             = random_bytes( 10 );
			$bits              = '';
			self::$last_random = array();
			for ( $i = 0; $i < 10; $i++ ) {
				$bits .= str_pad( decbin( ord( $bytes[ $i ] ) ), 8, '0', STR_PAD_LEFT );
			}
			foreach ( str_split( $bits, 5 ) as $chunk ) {
				self::$last_random[] = (int) bindec( $chunk );
			}
		}
		self::$last_time = $time;

		$out = '';
		for ( $i = 0; $i < 10; $i++ ) {
			$out  = self::ULID_ALPHABET[ $time % 32 ] . $out;
			$time = intdiv( $time, 32 );
		}
		foreach ( self::$last_random as $digit ) {
			$out .= self::ULID_ALPHABET[ $digit ];
		}

		return $out;
	}

	/**
	 * Current time as a UTC MySQL DATETIME string.
	 *
	 * @param int|null $timestamp Unix timestamp, defaults to now.
	 * @return string
	 */
	public static function now( $timestamp = null ) {
		return gmdate( 'Y-m-d H:i:s', null === $timestamp ? time() : $timestamp );
	}
}
