// Copies the reference portal's stylesheet (site-changelog.html <style>…</style>) into
// src/styles/portal.css so the app matches its look. The reference file is never modified.
//
//   node extract-styles.mjs
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const html = readFileSync(join(here, '../../site-changelog.html'), 'utf8');
const css = html.slice(html.indexOf('<style>') + 7, html.indexOf('</style>'));

writeFileSync(
	join(here, 'src/styles/portal.css'),
	'/* Generated by app/extract-styles.mjs from site-changelog.html — do not edit; add overrides to app.css. */\n' + css.trim() + '\n'
);
console.log(`Wrote ${css.length} bytes.`);
