<?php
/**
 * Tests for GRP_Cycles against fixtures generated by running the reference portal's
 * own functions (tests/fixtures/generate-cycles.mjs).
 *
 * @package GridRankers_Portal
 */

/**
 * Cycle / week / due-date maths.
 */
class Test_GRP_Cycles extends WP_UnitTestCase {

	/**
	 * Decoded fixture file.
	 *
	 * @var array|null
	 */
	private static $fixture = null;

	/**
	 * Loads the fixtures once.
	 *
	 * @return array
	 */
	private static function fixture() {
		if ( null === self::$fixture ) {
			self::$fixture = json_decode( file_get_contents( __DIR__ . '/fixtures/cycles.json' ), true ); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_get_contents_file_get_contents
		}

		return self::$fixture;
	}

	/**
	 * One data set per "now" date in the fixtures.
	 *
	 * @return array
	 */
	public function cases() {
		$out = array();
		foreach ( self::fixture()['cases'] as $i => $case ) {
			$out[ $case['now'] ] = array( $i );
		}

		return $out;
	}

	/**
	 * A PHP period in the fixture's compact shape.
	 *
	 * @param array $p Period from GRP_Cycles.
	 * @return array
	 */
	private function compact( array $p ) {
		$o = array(
			'key'   => $p['key'],
			'start' => $p['start'],
			'end'   => $p['end'],
			'day'   => $p['day'],
		);
		foreach ( array( 'cut', 'merged', 'transition' ) as $flag ) {
			if ( $p[ $flag ] ) {
				$o[ $flag ] = true;
			}
		}
		if ( $p['monthly'] ) {
			$o['monthly'] = $p['monthly'];
		}
		if ( $p['change'] ) {
			$o['change_from'] = $p['change']['from'];
		}

		return $o;
	}

	/**
	 * Calendar months. (The reference's calendar-month weeks are no longer used: weeks
	 * follow the project cycle, SPEC.md 6.2, tested below.)
	 *
	 * @dataProvider cases
	 *
	 * @param int $i Case index.
	 */
	public function test_months_match_reference( $i ) {
		$case  = self::fixture()['cases'][ $i ];
		$today = $case['now'];

		foreach ( $case['months'] as $off => $month ) {
			$this->assertSame( $month, GRP_Cycles::month_range( (int) $off, $today ), "month $off" );
		}
	}

	/**
	 * Periods, cycle ranges, cycleAt and due dates for every project.
	 *
	 * @dataProvider cases
	 *
	 * @param int $i Case index.
	 */
	public function test_project_cycles_match_reference( $i ) {
		$fixture = self::fixture();
		$case    = $fixture['cases'][ $i ];
		$today   = $case['now'];

		foreach ( $case['projects'] as $name => $expected ) {
			$project = $fixture['projects'][ $name ];

			if ( null !== $expected['periods'] ) {
				$this->assertSame(
					$expected['periods'],
					array_map( array( $this, 'compact' ), GRP_Cycles::periods_of( $project, $today ) ),
					"$name periods"
				);
			}

			foreach ( $expected['ranges'] as $off => $range ) {
				$this->assertSame( $range, $this->compact( GRP_Cycles::cycle_range( $project, (int) $off, $today ) ), "$name range $off" );
			}

			foreach ( $expected['at'] as $date => $range ) {
				$this->assertSame( $range, $this->compact( GRP_Cycles::cycle_at( $project, $date, $today ) ), "$name at $date" );
			}

			foreach ( $expected['due'] as $task_name => $by_off ) {
				$task = $fixture['tasks'][ $task_name ];
				foreach ( $by_off as $off => $due ) {
					// Weekly tasks (array fixtures) used calendar weeks in the reference; see the cycle-week tests.
					if ( ! is_array( $due ) ) {
						$this->assertSame( $due, GRP_Cycles::due_at( $task, $project, null, (int) $off, $today ), "$name $task_name off $off" );
					}
				}
			}
		}
	}

	public function test_accepts_database_rows() {
		$row = array(
			'cycle_day'     => '20',
			'cycle_changes' => wp_json_encode(
				array(
					array(
						'from'    => '2026-03-10',
						'day'     => 20,
						'prevDay' => 1,
						'mode'    => 'due',
					),
				)
			),
		);
		$ref = self::fixture()['projects']['due'];

		$this->assertSame( GRP_Cycles::periods_of( $ref, '2026-10-01' ), GRP_Cycles::periods_of( $row, '2026-10-01' ) );
		$this->assertSame(
			GRP_Cycles::due_at( array( 'dueDay' => 10 ), $ref, null, 0, '2026-10-01' ),
			GRP_Cycles::due_at( array( 'due_day' => '10' ), $row, null, 0, '2026-10-01' )
		);
	}

	public function test_period_keys_and_record_ids() {
		$project = array( 'cycle_day' => 15 );

		$this->assertSame( '2026-09', GRP_Cycles::period_key( array( 'freq' => 'monthly' ), $project, null, 0, '2026-10-01' ) );
		$this->assertSame( '2026-10', GRP_Cycles::period_key( array( 'freq' => 'monthly' ), $project, null, 0, '2026-10-20' ) );
		// Cycle Sep 15 – Oct 14: Oct 1 is in W3 (Sep 29 – Oct 5).
		$this->assertSame( '2026-09-w3', GRP_Cycles::period_key( array( 'freq' => 'weekly' ), $project, null, 0, '2026-10-01' ) );
		// Cycle Oct 15 – Nov 14: Oct 31 is in W3 (Oct 29 – Nov 4).
		$this->assertSame( '2026-10-w3', GRP_Cycles::period_key( array( 'freq' => 'weekly' ), $project, null, 0, '2026-10-31' ) );
		$this->assertSame( '2026-09-w2', GRP_Cycles::period_key( array( 'freq' => 'weekly' ), $project, 1, -1, '2026-10-31' ) );
		$this->assertSame( 'task1__2026-09', GRP_Cycles::record_id( 'task1', '2026-09' ) );
	}

	/**
	 * Start/end pairs of a list of weeks.
	 *
	 * @param array[] $weeks Weeks.
	 * @return string[]
	 */
	private function spans( array $weeks ) {
		return array_map(
			static function ( $w ) {
				return $w['start'] . '..' . $w['end'];
			},
			$weeks
		);
	}

	public function test_weeks_follow_the_project_cycle() {
		$project = array( 'cycle_day' => 15 );

		$this->assertSame(
			array( '2026-10-15..2026-10-21', '2026-10-22..2026-10-28', '2026-10-29..2026-11-04', '2026-11-05..2026-11-14' ),
			$this->spans( GRP_Cycles::weeks_of( $project, 0, '2026-10-20' ) )
		);
		$this->assertSame( 0, GRP_Cycles::active_week( $project, 0, '2026-10-15' ) );
		$this->assertSame( 2, GRP_Cycles::active_week( $project, 0, '2026-11-04' ) );
		$this->assertSame( 3, GRP_Cycles::active_week( $project, 0, '2026-11-14' ) );
		$this->assertSame( 3, GRP_Cycles::active_week( $project, -1, '2026-10-20' ), 'past cycle: last week' );
		$this->assertSame( 0, GRP_Cycles::active_week( $project, 1, '2026-10-20' ), 'future cycle: first week' );

		$weekly = array( 'freq' => 'weekly' );
		$this->assertSame( '2026-10-28', GRP_Cycles::due_at( $weekly, $project, null, 0, '2026-10-25' ) );
		$this->assertSame( '2026-11-14', GRP_Cycles::due_at( $weekly, $project, 3, 0, '2026-10-25' ) );
		$this->assertSame( array( '2026-11-05', '2026-11-14' ), array_values( GRP_Cycles::week_range( $project, 9, 0, '2026-10-25' ) ), 'clamped to the last week' );
	}

	public function test_day_one_projects_keep_calendar_weeks() {
		$this->assertSame(
			array( '2026-02-01..2026-02-07', '2026-02-08..2026-02-14', '2026-02-15..2026-02-21', '2026-02-22..2026-02-28' ),
			$this->spans( GRP_Cycles::weeks_of( array( 'cycle_day' => 1 ), 0, '2026-02-10' ) )
		);
		$this->assertSame(
			array( '2026-10-01..2026-10-07', '2026-10-08..2026-10-14', '2026-10-15..2026-10-21', '2026-10-22..2026-10-31' ),
			$this->spans( GRP_Cycles::weeks_of( array( 'cycle_day' => 1 ), 0, '2026-10-10' ) )
		);
		$this->assertSame( '2026-10-w3', GRP_Cycles::period_key( array( 'freq' => 'weekly' ), array( 'cycle_day' => 1 ), null, 0, '2026-10-16' ) );
	}

	public function test_short_and_long_periods_have_fewer_or_more_weeks() {
		$span = static function ( $start, $end ) {
			return GRP_Cycles::weeks_in(
				array(
					'start' => $start,
					'end'   => $end,
				)
			);
		};

		// A 14-day transition period: 2 weeks.
		$this->assertSame( array( '2026-10-01..2026-10-07', '2026-10-08..2026-10-14' ), $this->spans( $span( '2026-10-01', '2026-10-14' ) ) );
		// 10 days: one week that takes them all.
		$this->assertSame( array( '2026-10-01..2026-10-10' ), $this->spans( $span( '2026-10-01', '2026-10-10' ) ) );
		// 3 days: still one week.
		$this->assertSame( array( '2026-10-12..2026-10-14' ), $this->spans( $span( '2026-10-12', '2026-10-14' ) ) );
		// A merged 45-day period: 6 weeks, the last one 10 days.
		$long = $span( '2026-10-01', '2026-11-14' );
		$this->assertCount( 6, $long );
		$this->assertSame( '2026-11-05..2026-11-14', $this->spans( $long )[5] );
	}

	public function test_biweekly_tasks_use_two_week_periods() {
		$project  = array( 'cycle_day' => 15 );
		$biweekly = array( 'freq' => 'biweekly' );
		$cycle    = GRP_Cycles::cycle_range( $project, 0, '2026-10-20' );

		$halves = GRP_Cycles::halves_in( $cycle );
		$this->assertSame( array( '2026-10-15..2026-10-28', '2026-10-29..2026-11-14' ), $this->spans( $halves ) );
		$this->assertSame( array( 1, 2 ), array( $halves[0]['from_week'], $halves[0]['to_week'] ) );
		$this->assertSame( array( 3, 4 ), array( $halves[1]['from_week'], $halves[1]['to_week'] ) );

		$this->assertSame( '2026-10-h1', GRP_Cycles::period_key( $biweekly, $project, null, 0, '2026-10-20' ) );
		$this->assertSame( '2026-10-h2', GRP_Cycles::period_key( $biweekly, $project, null, 0, '2026-11-02' ) );
		$this->assertSame( '2026-10-28', GRP_Cycles::due_at( $biweekly, $project, null, 0, '2026-10-20' ) );
		$this->assertSame( '2026-11-14', GRP_Cycles::due_at( $biweekly, $project, 1, 0, '2026-10-20' ) );
		$this->assertSame( 1, GRP_Cycles::active_slot( $biweekly, $project, -1, '2026-10-20' ), 'past cycle: last period' );
		$this->assertNull( GRP_Cycles::slots_in( array( 'freq' => 'monthly' ), $cycle ) );
	}

	public function test_two_week_periods_of_short_and_long_periods() {
		$span = static function ( $start, $end ) {
			return GRP_Cycles::halves_in(
				array(
					'start' => $start,
					'end'   => $end,
				)
			);
		};
		// 14-day transition: one two-week period.
		$this->assertSame( array( '2026-10-01..2026-10-14' ), $this->spans( $span( '2026-10-01', '2026-10-14' ) ) );
		// 10 days: one.
		$this->assertCount( 1, $span( '2026-10-01', '2026-10-10' ) );
		// 5 weeks (35–41 days): weeks 1–2, then 3–5.
		$five = $span( '2026-10-01', '2026-11-04' );
		$this->assertSame( array( '2026-10-01..2026-10-14', '2026-10-15..2026-11-04' ), $this->spans( $five ) );
		$this->assertSame( array( 3, 5 ), array( $five[1]['from_week'], $five[1]['to_week'] ) );
		// 6 weeks: three.
		$this->assertCount( 3, $span( '2026-10-01', '2026-11-14' ) );
	}

	public function test_transition_period_weeks() {
		// Day 1 → day 15 from Oct 1 with a transition: Oct 1–14 has two weeks.
		$project = array(
			'cycle_day'     => 15,
			'cycle_changes' => array(
				array(
					'from'    => '2026-10-01',
					'day'     => 15,
					'prevDay' => 1,
					'mode'    => 'due',
				),
			),
		);
		$this->assertSame( 'T2026-10-01', GRP_Cycles::cycle_range( $project, 0, '2026-10-05' )['key'] );
		$this->assertSame( array( '2026-10-01..2026-10-07', '2026-10-08..2026-10-14' ), $this->spans( GRP_Cycles::weeks_of( $project, 0, '2026-10-05' ) ) );
		$this->assertSame( 'T2026-10-01-w2', GRP_Cycles::period_key( array( 'freq' => 'weekly' ), $project, null, 0, '2026-10-09' ) );

		list( $period, $w ) = GRP_Cycles::week_at( $project, '2026-10-30', '2026-10-05' );
		$this->assertSame( '2026-10', $period['key'] );
		$this->assertSame( 2, $w );
	}
}
