<?php
/**
 * Tests for GRP_Cycles against fixtures generated by running the reference portal's
 * own functions (tests/fixtures/generate-cycles.mjs).
 *
 * @package GridRankers_Portal
 */

/**
 * Cycle / week / due-date maths.
 */
class Test_GRP_Cycles extends WP_UnitTestCase {

	/**
	 * Decoded fixture file.
	 *
	 * @var array|null
	 */
	private static $fixture = null;

	/**
	 * Loads the fixtures once.
	 *
	 * @return array
	 */
	private static function fixture() {
		if ( null === self::$fixture ) {
			self::$fixture = json_decode( file_get_contents( __DIR__ . '/fixtures/cycles.json' ), true ); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_get_contents_file_get_contents
		}

		return self::$fixture;
	}

	/**
	 * One data set per "now" date in the fixtures.
	 *
	 * @return array
	 */
	public function cases() {
		$out = array();
		foreach ( self::fixture()['cases'] as $i => $case ) {
			$out[ $case['now'] ] = array( $i );
		}

		return $out;
	}

	/**
	 * A PHP period in the fixture's compact shape.
	 *
	 * @param array $p Period from GRP_Cycles.
	 * @return array
	 */
	private function compact( array $p ) {
		$o = array(
			'key'   => $p['key'],
			'start' => $p['start'],
			'end'   => $p['end'],
			'day'   => $p['day'],
		);
		foreach ( array( 'cut', 'merged', 'transition' ) as $flag ) {
			if ( $p[ $flag ] ) {
				$o[ $flag ] = true;
			}
		}
		if ( $p['monthly'] ) {
			$o['monthly'] = $p['monthly'];
		}
		if ( $p['change'] ) {
			$o['change_from'] = $p['change']['from'];
		}

		return $o;
	}

	/**
	 * Months, weeks and active week.
	 *
	 * @dataProvider cases
	 *
	 * @param int $i Case index.
	 */
	public function test_months_and_weeks_match_reference( $i ) {
		$case  = self::fixture()['cases'][ $i ];
		$today = $case['now'];

		foreach ( $case['months'] as $off => $month ) {
			$this->assertSame( $month, GRP_Cycles::month_range( (int) $off, $today ), "month $off" );
			$this->assertSame( $case['activeWeek'][ $off ], GRP_Cycles::active_week( (int) $off, $today ), "active week $off" );
			foreach ( $case['weeks'][ $off ] as $w => $week ) {
				$this->assertSame( $week, GRP_Cycles::week_range( $w, (int) $off, $today ), "week $w of month $off" );
			}
		}
	}

	/**
	 * Periods, cycle ranges, cycleAt and due dates for every project.
	 *
	 * @dataProvider cases
	 *
	 * @param int $i Case index.
	 */
	public function test_project_cycles_match_reference( $i ) {
		$fixture = self::fixture();
		$case    = $fixture['cases'][ $i ];
		$today   = $case['now'];

		foreach ( $case['projects'] as $name => $expected ) {
			$project = $fixture['projects'][ $name ];

			if ( null !== $expected['periods'] ) {
				$this->assertSame(
					$expected['periods'],
					array_map( array( $this, 'compact' ), GRP_Cycles::periods_of( $project, $today ) ),
					"$name periods"
				);
			}

			foreach ( $expected['ranges'] as $off => $range ) {
				$this->assertSame( $range, $this->compact( GRP_Cycles::cycle_range( $project, (int) $off, $today ) ), "$name range $off" );
			}

			foreach ( $expected['at'] as $date => $range ) {
				$this->assertSame( $range, $this->compact( GRP_Cycles::cycle_at( $project, $date, $today ) ), "$name at $date" );
			}

			foreach ( $expected['due'] as $task_name => $by_off ) {
				$task = $fixture['tasks'][ $task_name ];
				foreach ( $by_off as $off => $due ) {
					if ( is_array( $due ) ) {
						$this->assertSame( $due['active'], GRP_Cycles::due_at( $task, $project, null, (int) $off, $today ), "$name $task_name active week, off $off" );
						foreach ( $due['weeks'] as $w => $week_due ) {
							$this->assertSame( $week_due, GRP_Cycles::due_at( $task, $project, $w, (int) $off, $today ), "$name $task_name week $w, off $off" );
						}
					} else {
						$this->assertSame( $due, GRP_Cycles::due_at( $task, $project, null, (int) $off, $today ), "$name $task_name off $off" );
					}
				}
			}
		}
	}

	public function test_accepts_database_rows() {
		$row = array(
			'cycle_day'     => '20',
			'cycle_changes' => wp_json_encode(
				array(
					array(
						'from'    => '2026-03-10',
						'day'     => 20,
						'prevDay' => 1,
						'mode'    => 'due',
					),
				)
			),
		);
		$ref = self::fixture()['projects']['due'];

		$this->assertSame( GRP_Cycles::periods_of( $ref, '2026-10-01' ), GRP_Cycles::periods_of( $row, '2026-10-01' ) );
		$this->assertSame(
			GRP_Cycles::due_at( array( 'dueDay' => 10 ), $ref, null, 0, '2026-10-01' ),
			GRP_Cycles::due_at( array( 'due_day' => '10' ), $row, null, 0, '2026-10-01' )
		);
	}

	public function test_period_keys_and_record_ids() {
		$project = array( 'cycle_day' => 15 );

		$this->assertSame( '2026-09', GRP_Cycles::period_key( array( 'freq' => 'monthly' ), $project, null, 0, '2026-10-01' ) );
		$this->assertSame( '2026-10', GRP_Cycles::period_key( array( 'freq' => 'monthly' ), $project, null, 0, '2026-10-20' ) );
		$this->assertSame( '2026-10-w1', GRP_Cycles::period_key( array( 'freq' => 'weekly' ), $project, null, 0, '2026-10-01' ) );
		$this->assertSame( '2026-10-w4', GRP_Cycles::period_key( array( 'freq' => 'weekly' ), $project, null, 0, '2026-10-31' ) );
		$this->assertSame( '2026-09-w2', GRP_Cycles::period_key( array( 'freq' => 'weekly' ), $project, 1, -1, '2026-10-31' ) );
		$this->assertSame( 'task1__2026-09', GRP_Cycles::record_id( 'task1', '2026-09' ) );
	}

	public function test_calendar_month_weeks() {
		$this->assertSame(
			array(
				array(
					'start' => '2026-02-01',
					'end'   => '2026-02-07',
				),
				array(
					'start' => '2026-02-08',
					'end'   => '2026-02-14',
				),
				array(
					'start' => '2026-02-15',
					'end'   => '2026-02-21',
				),
				array(
					'start' => '2026-02-22',
					'end'   => '2026-02-28',
				),
			),
			array_map(
				static function ( $w ) {
					return GRP_Cycles::week_range( $w, 0, '2026-02-10' );
				},
				array( 0, 1, 2, 3 )
			)
		);
	}
}
